# Generated by Django 4.2.2 on 2023-07-05 11:24

from django.db import migrations, models
import movie.models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_tag_movie_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=movie.models.image_upload_path),
        ),
    ]
